name: CI (AquaManager - local)

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  backend:
    name: Backend (NestJS)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install backend dependencies
        working-directory: back_end
        run: npm ci

      - name: Build backend
        working-directory: back_end
        run: npm run build
        

  frontend:
    name: Frontend (Angular)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install frontend dependencies
        working-directory: front_end/web
        run: npm ci

      - name: Build frontend
        working-directory: front_end/web
        run: npm run build
